### ISSUE TITLE
error clicking on Joystick Gremlin row when running

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#113] opened 2018-05-31 23:58 UTC
I have created a Macro row with on edutton when pressed and one button when released 
when i enable Joystick Gremlin and then press the button on joy if i click on the MACRO ROW in Joystick Gremlin i get this exception 

```2018-06-01 01:50:44      DEBUG 5 joysticks found
2018-06-01 01:50:44      DEBUG 5 joysticks found
2018-06-01 01:50:44      ERROR Requested vJoy 1 device is not available
2018-06-01 01:50:44      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 392, in input_item_selected_cb
   File "gremlin\ui\device_tab.py", line 61, in __init__
   File "gremlin\ui\device_tab.py", line 274, in redraw
   File "container_plugins\basic\__init__.py", line 35, in __init__
    super().__init__(profile_data, parent)
   File "gremlin\ui\input_item.py", line 636, in __init__
   File "gremlin\ui\input_item.py", line 679, in _create_activation_condition_tab
   File "container_plugins\basic\__init__.py", line 74, in _create_condition_ui
    widget.redraw()
   File "gremlin\ui\input_item.py", line 383, in redraw
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\macro\__init__.py", line 1011, in __init__
    super().__init__(action_data, parent)
   File "gremlin\ui\input_item.py", line 812, in __init__
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\macro\__init__.py", line 1204, in _populate_ui
    self._edit_action(self.model.index(0, 0))
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\macro\__init__.py", line 1211, in _edit_action
    self.editor_widget = MacroActionEditor(self.model, model_index)
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\macro\__init__.py", line 65, in __init__
    self._populate_ui()
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\macro\__init__.py", line 99, in _populate_ui
    self._vjoy_ui()
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\macro\__init__.py", line 282, in _vjoy_ui
    gremlin.common.InputType.JoystickHat
   File "gremlin\ui\common.py", line 694, in __init__
   File "gremlin\ui\common.py", line 803, in _create_input_dropdown
   File "gremlin\joystick_handling.py", line 49, in __getitem__
   File "vjoy\vjoy.py", line 351, in __init__
 gremlin.error.VJoyError: 'Requested vJoy 1 device is not available'```

**Comment by WhiteMagic** [comment] 2018-12-21 14:33
This should be fixed with recent changes that handle the inability to get hold of vJoy devices more gracefully. Though I couldn't reproduce this particular crash the general type of error should no longer be able to be triggered.

**Closed by WhiteMagic** 2018-12-21 14:33 UTC
Labels: bug
