### ISSUE TITLE
Sendkey instead of button

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#61] opened 2017-07-23 22:34 UTC
I need to implement F9 F12 for to lock and centre TrackIR that is not able to use joy button.
i'm looking inside your example but  and i find something like this (there is also pulse option and Shift button S3) but when i run it i get the error that AttributeError: 'module' object has not attribute 'Keys' :
`
import threading
import time

import gremlin

fssR3 = gremlin.input_devices.JoystickDecorator(
    "FSSB R3 MJF",
    316678145,
    "Default"
)

tusba = gremlin.input_devices.JoystickDecorator(
    "TUSBA TQS R2",
    316674052,
    "Default"
)

# Maximum duration of a "short" press
g_timeout = 0.3
# Seconds to hold the button pressed
g_hold_time = 0.1
# Seconds to wait between releasing and pressing the button again
g_pause_time = 0.1
# Timer object triggering the "long press"
g_timer = None
# Flag indicating if the pulse action is running or should be stopped
g_is_running = True

# Assumption same key for both short and long press, but long press will start
# to pulse the key instead of just holding it down.

# Macros to send the TrackIR F9 / F12 ccommands
lockTrackIR = gremlin.macro.Macro()
lockTrackIR.tap(gremlin.macro.Keys.F12)
centerTrackIR = gremlin.input_devices.macro.Macro()
centerTrackIR.tap(gremlin.macro.Keys.F9)

def pulse(vjoy, position):
    """Runs the long press macro repeatedly with a pause in between executions.

    :param vjoy the vJoy proxy object
    :param btn_id the id of the button to press and release in the pulse
    """
    global g_is_running
    g_is_running = True
    while g_is_running:
        vjoy[1].hat(1).direction = position
        time.sleep(g_hold_time)
        vjoy[1].hat(1).direction = (0,0)
        time.sleep(g_pause_time)

@fssR3.hat(1)
def hat1(event, joy, vjoy):
    # Id of the button to press or pulse

    global g_is_running, g_timer

    position = event.value

    if joy[1].button(3).is_pressed:
        if  position == (-1,0) or position == (1,0):
            # Hat a sx HSI decrease or dx HSI increase
            vjoy[1].hat(1).direction = position
            # Start a timer so we can transition to pulsing when the button
            # is held down long enough
            g_timer = threading.Timer(g_timeout, lambda: pulse(vjoy, position))
            g_timer.start()
        elif position == (0, 1):
            # Hat up F12
            centerTrackIR.run()
        elif position == (0, -1):
            # Hat down F9
            lockTrackIR.run()
    else:
        #stop pulse
        g_is_running = False
        if g_timer:
            g_timer.cancel()
        #return HAT
        vjoy[1].hat(1).direction = position
`

**Comment by Francky63** [comment] 2017-07-23 23:53
sorry i found some bugs... the method that is not recognized in run()

import threading
import time

import gremlin


fssR3 = gremlin.input_devices.JoystickDecorator(
    "FSSB R3 MJF",
    316678145,
    "Default"
)

tusba = gremlin.input_devices.JoystickDecorator(
    "TUSBA TQS R2",
    316674052,
    "Default"
)

# Maximum duration of a "short" press
g_timeout = 0.3
# Seconds to hold the button pressed
g_hold_time = 0.1
# Seconds to wait between releasing and pressing the button again
g_pause_time = 0.1
# Timer object triggering the "long press"
g_timer = None
# Flag indicating if the pulse action is running or should be stopped
g_is_running = True


# Assumption same key for both short and long press, but long press will start
# to pulse the key instead of just holding it down.

# Macros to send the TrackIR F9 / F12 ccommands
lockTrackIR = gremlin.input_devices.macro.Macro()
lockTrackIR.tap("F9")
centerTrackIR = gremlin.input_devices.macro.Macro()
centerTrackIR.tap("F12")


def pulse(vjoy, position):
    """Runs the long press macro repeatedly with a pause in between executions.

    :param vjoy the vJoy proxy object
    :param btn_id the id of the button to press and release in the pulse
    """
    global g_is_running, centerTrackIR, lockTrackIR 
    g_is_running = True
    while g_is_running:
        vjoy[1].hat(1).direction = position
        time.sleep(g_hold_time)
        vjoy[1].hat(1).direction = (0,0)
        time.sleep(g_pause_time)

@fssR3.hat(1)
def hat1(event, joy, vjoy):
    # Id of the button to press or pulse

    global g_is_running, g_timer

    position = event.value

    if joy[1].button(3).is_pressed:
        if  position == (-1,0) or position == (1,0):
            # Hat a sx HSI decrease or dx HSI increase
            vjoy[1].hat(1).direction = position
            # Start a timer so we can transition to pulsing when the button
            # is held down long enough
            g_timer = threading.Timer(g_timeout, lambda: pulse(vjoy, position))
            g_timer.start()
        elif position == (0, 1):
            # Hat up F12
            centerTrackIR.run()
        elif position == (0, -1):
            # Hat down F9
            lockTrackIR.run()
        else:
            #stop pulse
            g_is_running = False
            if g_timer:
                g_timer.cancel()
            #return HAT
            vjoy[1].hat(1).direction = position
    else:
        #stop pulse
        g_is_running = False
        if g_timer:
            g_timer.cancel()
        #return HAT
        vjoy[1].hat(1).direction = position

**Comment by WhiteMagic** [comment] 2017-07-24 01:12
The main problem is that the example you're using as a basis was written for R7 and the macro system was quite heavily changed for R8. This is the reason that there is no longer a Keys class in the macro module nor a run() method on Macro object instances anymore. When I get home I'll have a look into porting the example over to the current system but in the meantime here are the main changes.

Macro objects don't execute themselves anymore as there is a MacroManager which takes care of scheduling them. Typically that means just running them but this also allows a macro to ensure that only it is run an nothing else, mainly to prevent crosstalk between macros. This also allows to have macros repeat etc. essentially this enables all the options you see in the UI.

The other big change was the way keyboard keys are named / found etc. R7 and earlier would deal very badly with non US keyboards as everything was hard coded. An example would be the Z and Y key on a German keyboard which are swapped as compared to a US keyboard. These keys all were part of this macro.Keys object. With R8 Gremlin tries to be a bit better when it comes to keyboard layout and language, though I have no doubt that it will break in interesting ways because of it. As a consequence only certain keys are hardcoded, function keys, arrows, etc. So now in order to get the desired key you have to use a function "key_from_name". This function will try to find the corresponding key and return it if it can find it. As you've found you you can pass a simple string to the press / tap / release methods of a macro which will forward it properly to this function and do the key lookup for you.

The only change to make your examples work should be to replace the .run() call with the following:
`gremlin.macro.MacroManager().add_macro(centerTrackIR, None, event)`
where you replace centerTrackIR with the corresponding macro object name wherever there is a macro_object.run() call.

Also it seems that the easiest way to have the UI be able to deal with such usages would be to have a generic condition that depends on the state of some other input such as a joystick or keyboard.

**Comment by Francky63** [comment] 2017-07-24 11:19
perfect it works fine

**Comment by Francky63** [comment] 2017-07-28 20:18
Apparently it works
I'll explain, as  i wrote  I use this trick to get the center and lock TrackIR function (available only by keyboard),  it works only if the focus in on windows desktop, if the focus is in TrackIR window it doesn't 'fill' key depress and, most important doesn't work in Falcon

**Comment by WhiteMagic** [comment] 2017-07-29 13:33
This is odd. I can reproduce the problem you have with TrackIR ignoring the joystick remap to a keyboard button to trigger the center action when the TrackIR window is focused. I've used a similar mapping from joystick to keyboard button to center TrackIR in a few games and it always worked, so there must be something specific about Falcon and TrackIR that prevents the keyboard input from ever reaching Gremlin I'd imagine.

One thing you could try is to launch Gremlin as administrator, maybe that allows it to get the input even if Falcon somehow prevents its propagation. Another thing is that I can actually map joystick buttons to center, etc. actions in the TrackIR software (version 5.4.2.27545) maybe this is something that was only added recently?

**Comment by WhiteMagic** [comment] 2018-03-26 00:56
Closing for now, feel free to reopen this if there are more issues around this.

**Closed by WhiteMagic** 2018-03-26 00:56 UTC
