### ISSUE TITLE
JG seems to simulate the release of the keyboard key twice !?

### ISSUE THREAD

**Issue by ecidou** [WhiteMagic/JoystickGremlin#307] opened 2020-07-10 17:20 UTC
Hello 
(and first of all I'd like to take this opportunity to thank you for your software)

As i go deeper in it, i've found a strange behaviour highlighted by the **test function of the Logitech Profiler** (i have a X52 Pro) :

1. I pressed the **real** C key => i see on the test windows : "C" pressed "C" released
2. Now with JG thru a basic "**Map to Keyboard**" : C" pressed "C" released **"C" released** 

[Screenshoot](https://1drv.ms/u/s!Am_-yrC4_SQ_vCXT0rIuRw6If1wq?e=44SXHg) if needed
(And this for the whole keys)

Any idea ?

**Comment by WhiteMagic** [comment] 2020-07-12 06:13
I'd have to look deeper into the code but this could be correct. The reason you can get two release actions is that Gremlin does some magic behind to scenes to ensure a "release" action is triggered on inputs even if the mode changes between the "press" and "release" action. As releasing a key twice doesn't change its state I at some point removed complex tracking logic that would ensure this would only happen when needed, as it caused a bunch of weird bugs.

If/when I get back to reworking that feature I might actually just use a FSM which would take care of this.

**Comment by WhiteMagic** [comment] 2020-08-22 12:16
Duplicate of  #254.

**Closed as completed by WhiteMagic** 2020-08-22 12:16 UTC
