### ISSUE TITLE
Adding Configurable Variables to an existing User Plugin breaks ability to save

### ISSUE THREAD

**Issue by GameOverture** [WhiteMagic/JoystickGremlin#209] opened 2019-04-19 03:13 UTC
![image](https://user-images.githubusercontent.com/344924/56403346-e4e8f200-622e-11e9-8cf1-954bffff6404.png)
This error occurs when adding (and maybe also modifying) a Configurable Variables to a User Plugin that already exists in the profile's XML and trying to Save. A work around is removing the instance of the user plugin, save, then remap all the variables.

**Comment by WhiteMagic** [comment] 2019-04-21 02:32
Hm yeah that sounds like something that's entirely plausible. I'll have to look into the code to see if just trapping the error and nuking the configuration is fine or if some better logic is needed.

**Comment by WhiteMagic** [comment] 2019-04-25 01:54
Should be fixed with 24dd59d28ffdc9a176bad6a3e4ac7e2ffd0d2528 though the issue is somewhat related to #213 which should make this nicer.

The issue was that Gremlin thought the profile was valid to save, since it was able to load it and because there is no concept of a partially configured plugin or optional variables saving things failed.

**Closed by WhiteMagic** 2019-04-25 01:54 UTC
Labels: bug
