### ISSUE TITLE
Need to replug physical devices everytime when using HIDGuardian

### ISSUE THREAD

**Issue by LeLooong** [WhiteMagic/JoystickGremlin#225] opened 2019-07-20 07:52 UTC
Since v13, when JoystickGremlin is used with HidGuardian to hide physical devices, JG don't see the physicals devices on launch.
I need to replug the devices after I launched JG in order to display them.
Then it works well... until JG next launch.

If I uninstall HidGuardian and HidCerberus (with WhiteKnight Auto-Whitelister) then the physical devices are correctly seen on every JG launch.

PS: 1st time I write to you so I take the opportunity to thanks you for your work, JG is so useful to me!

**Comment by WhiteMagic** [comment] 2019-07-20 08:07
I'm assuming you're running Gremlin as admin, as otherwise you would never be able to see the devices, even after re-plugging them. The only change to the hidguardian code in Gremlin was a bug with device identifiers, though that shouldn't have affected the part that seems to be causing issues, i.e. whitelisting of Gremlin.

How did you install hidguardian, just so I can reproduce that particular setup if needed. I'll have to look into why Gremlin might not see the device upon launch, it could be that there is something different in how / when Gremlin scans for devices as that part changed in R13. If the device scan happens before the HidGuardian whitelisting of Gremlin then that could explain what you're seeing.

**Comment by LeLooong** [comment] 2019-07-20 08:33
Yes I run Gremlin as admin.

Not sure how to describe how I install hidguardian, just did again this sequence:
- I use AutoWhitelister.exe from WhiteKnight that I launch as admin.
- I click on "install HidGuardian" + "install HidCerberus".
- Then I can access the HidGuardian configuration interface.
- In Gremlin options / HIDGuardian tab, I check the boxes for my 3 devices.
- I replug the 3 devices.
- I refresh HidGuardian config interface, my 3 physical devices are now displayed as "Currently affected devices".
- (I close both Autowhitelister and JG)
- (I relaunch JG and the 3 physical devices are hidden)

I have W10, just updated to build 1903 and already had the problem with the 1803.

I join the debug file if it can help. sequence: I launch JG, replug the 3 devices, close JG.
[LeLooong_debug.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3413365/LeLooong_debug.txt)

**Comment by WhiteMagic** [comment] 2019-07-20 16:15
I'll have to see if there is an issue with ordering of things, or maybe there is a weird interaction between hidguardian and dill (the input library) and that one ends up being unable to see the devices.

**Comment by WhiteMagic** [comment] 2019-07-21 12:16
Had a bit of a look and it turns out it was an issue with the order in which hidguardian and dill were initialized, i.e. dill looked for devices first and then hidguardian ran meaning dill couldn't see the devices. Changing things around a bit in a way that I can ensure hidguardian is initialized before dill solves this.

Fixed with: 750d85ee1d12cfb3942f36cd5b663c834af5788c

**Closed as completed by WhiteMagic** 2019-07-21 12:16 UTC
Labels: bug, minor-work

**Comment by Gekko23** [comment] 2021-02-02 16:11
The behavior OP describes is still an gamebreaking issue. Since Microsoft deleted the DirectX9 runtimes (https://www.microsoft.com/en-us/download/details.aspx?id=8109) that are needed to make DEVREORDER work (https://github.com/briankendall/devreorder), you now need the incredible annoying HidGuardian to make a functional Joystick Gremlin setup.

I had Joystick Gremlin running with DevReorder on another machine and it worked flawlessly. But with HidGuardian you have to replug each joystick device with every start (!) of Joystick Gremlin. This is the year 2021 calling: please stop programming software that behaves like 1994. Seriously. There are no workarounds for this annoyance but to program this correctly. I would strongly appreciate that. Thank you.
