### ISSUE TITLE
Monect Hid Device cause crash on startup

### ISSUE THREAD

**Issue by doniecm** [WhiteMagic/JoystickGremlin#161] opened 2018-11-24 10:46 UTC
I've installed PC Remote control program from monect com (it's a android > pc remote controller which emulates a joystick among other things)

It installs Monect Hid Device on PC. It causes joystick gremlin to crash on startup.
Log from R11 Debug 4 version of JG (found on this forum)
2018-11-24 10:38:40      DEBUG --------------------------------------------------------------------------------
2018-11-24 10:38:40      DEBUG 2018-11-24 10:38
2018-11-24 10:38:40      DEBUG Starting Joystick Gremlin R11.1
2018-11-24 10:38:40      DEBUG --------------------------------------------------------------------------------
2018-11-24 10:38:40       INFO Initializing joystick devices
2018-11-24 10:38:40      DEBUG 6 joysticks detected
2018-11-24 10:38:40      DEBUG Added: name=Monect Hid Device windows_id=5 hardware_id=3203399405
2018-11-24 10:38:40      DEBUG Added: name=Monect Hid Device windows_id=4 hardware_id=3203399405
2018-11-24 10:38:40      DEBUG Added: name=VPC-Throttle windows_id=3 hardware_id=65740872
2018-11-24 10:38:40      DEBUG Added: name=MFG Crosswind V2 windows_id=2 hardware_id=382732856
2018-11-24 10:38:40      DEBUG Added: name=VPC MT50 Flightstick windows_id=1 hardware_id=65740867
2018-11-24 10:38:40      DEBUG Added: name=vJoy Device windows_id=0 hardware_id=305446573
2018-11-24 10:38:40      DEBUG vJoy windows id 0: (8, 128, 4)
2018-11-24 10:38:40      DEBUG vjoy id 1: (8, 128, 4) - MATCH
2018-11-24 10:38:40       INFO Initializing joystick devices
2018-11-24 10:38:40      DEBUG 6 joysticks detected
2018-11-24 10:38:40       INFO Checking vJoy installation
2018-11-24 10:38:40       INFO Initializing plugins
2018-11-24 10:38:40      DEBUG Loaded: cycle-modes
2018-11-24 10:38:40       INFO Initializing joystick devices
2018-11-24 10:38:40      DEBUG 6 joysticks detected
2018-11-24 10:38:40       INFO Initializing joystick devices
2018-11-24 10:38:40      DEBUG 6 joysticks detected
2018-11-24 10:38:40      DEBUG Loaded: description
2018-11-24 10:38:40       INFO Initializing joystick devices
2018-11-24 10:38:40      DEBUG 6 joysticks detected
2018-11-24 10:38:40       INFO Initializing joystick devices
2018-11-24 10:38:40      DEBUG 6 joysticks detected
2018-11-24 10:38:40       INFO Initializing joystick devices
2018-11-24 10:38:40      DEBUG 6 joysticks detected
2018-11-24 10:38:40      DEBUG Loaded: macro
2018-11-24 10:38:40      DEBUG Loaded: map-to-keyboard
2018-11-24 10:38:40      DEBUG Loaded: map-to-mouse
2018-11-24 10:38:40      DEBUG Loaded: noop
2018-11-24 10:38:40      DEBUG Loaded: pause
2018-11-24 10:38:40      DEBUG Loaded: play-sound
2018-11-24 10:38:40      DEBUG Loaded: previous-mode
2018-11-24 10:38:40      DEBUG Loaded: remap
2018-11-24 10:38:40      DEBUG Loaded: response-curve
2018-11-24 10:38:40      DEBUG Loaded: resume
2018-11-24 10:38:40      DEBUG Loaded: split-axis
2018-11-24 10:38:40      DEBUG Loaded: switch-mode
2018-11-24 10:38:40      DEBUG Loaded: temporary-mode-switch
2018-11-24 10:38:40      DEBUG Loaded: text-to-speech
2018-11-24 10:38:40      DEBUG Loaded: toggle-pause
2018-11-24 10:38:40      DEBUG Loaded: basic
2018-11-24 10:38:40      DEBUG Loaded: chain
2018-11-24 10:38:40      DEBUG Loaded: hat_buttons
2018-11-24 10:38:40      DEBUG Loaded: tempo
2018-11-24 10:38:41      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 390, in input_item_selected_cb
   File "gremlin\ui\device_tab.py", line 50, in __init__
   File "gremlin\ui\device_tab.py", line 108, in _create_description
 AttributeError: 'NoneType' object has no attribute 'description'

Uninstalling remote control host from PC fixes the problem as it uninstalls Monect HID, but I'd rather keep it (it's really neat for creating virtual control panel for flight sims.)

Thank you,
M.

**Comment by WhiteMagic** [comment] 2018-11-24 21:14
This looks like it shouldn't be very hard to fix / check for this type of issue. It's a bit odd that this is happening so I'll have to look into what causes the issue on top of adding checks to handle this type of problem for future cases.

**Comment by WhiteMagic** [comment] 2018-11-25 06:08
Fixed with 949c72855e87e057e6e5e754a093e40052e21c02, crash was caused by the empty joystick device created by the app.

**Closed by WhiteMagic** 2018-11-25 06:08 UTC
Labels: bug, minor-work

**Comment by doniecm** [comment] 2018-11-25 09:34
Thank you for this great software and your dedication!
